import { COLOR_YELLOW, COLOR_BLUE, GREY_COLOR } from './colors'
import { TABLET } from './screen'
import { RESPONSIVE } from './slider'
import { DARK, LIGHT } from './theme'
import {
  COMPANY_URL,
  UDEMY_URL,
  UNIVERSITY_URL,
  TELEGRAM_URL,
  LINKEDIN_URL,
  EMAIL_URL,
  GIT_HUB,
  ASX_URL,
  TUTTIFY_URL,
  MAVEN_URL,
  CV_URL,
} from './URLs'

export {
  RESPONSIVE,
  TABLET,
  DARK,
  LIGHT,
  COLOR_YELLOW,
  COLOR_BLUE,
  GREY_COLOR,
  COMPANY_URL,
  UDEMY_URL,
  UNIVERSITY_URL,
  TELEGRAM_URL,
  LINKEDIN_URL,
  EMAIL_URL,
  GIT_HUB,
  ASX_URL,
  TUTTIFY_URL,
  MAVEN_URL,
  CV_URL,
}
