export { default as headerPhoto } from './images/header-pic.webp'
export { default as asx } from './images/site-mock.webp'
export { default as tutiffy } from './images/mock-site2.webp'
export { default as maven } from './images/mock-site3.webp'
export { default as asxPageFirst } from './images/asx-page1.webp'
export { default as asxPageSecond } from './images/asx-page2.webp'
export { default as tutiffyPageRirst } from './images/tut-page1.webp'
export { default as tutiffyPageSecond } from './images/tut-page2.webp'
export { default as mavenPageRirst } from './images/mav-page1.webp'
export { default as mavenPageSecond } from './images/mav-page2.webp'
export { default as chatPhoto } from './images/chat-img.webp'
export { default as elementicaHomePage } from './images/elementica.webp'
export { default as imtHomePage } from './images/imt.webp'
export { default as udemyHomePage } from './images/udemy.webp'

export { default as soundSendMessage } from './sounds/telegram-sound-send.mp3'
export { default as soundResponseMessage } from './sounds/telegram-sound-response.mp3'
